version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: 8.2
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-ChangeMe}
      DATABASE_URL: ${DATABASE_URL:-postgresql://app:app@database:5432/app}
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html:rw

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
