version: '3'
name: cumas

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: 8.2
    env_file:
      - ../.env
      - ../.env.dev
    ports:
      - 8000:80
    volumes:
      - ..:/var/www/html:rw

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    env_file:
      - ../.env
      - ../.env.dev
    ports:
      - 54321:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
